# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "beae3dcd552ef30b4b939f5099e1a416"
application_url = "https://example.com"
embedded = true
name = "Ship Rules Lite"

[access_scopes]
scopes = "read_products,read_delivery_customizations,write_delivery_customizations,read_validations,write_validations"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
